from __future__ import annotations

from sqlalchemy import select
from sqlalchemy.orm import Session

from .models import MediaItem


CATALOG = [
    dict(media_type="movie", title="Interstellar", language="English", runtime_minutes=169, commitment="long", popularity=.95, quality_prior=.93, tags=["space", "physics", "family", "time"], features={"philosophical_depth":.84,"narrative_complexity":.79,"world_building":.76,"emotional_intensity":.88,"scientific_grounding":.75,"pacing":.55,"darkness":.48,"originality":.82,"information_density":.55}, downsides=["Long runtime", "Emotional themes may outweigh scientific rigor"]),
    dict(media_type="movie", title="Arrival", language="English", runtime_minutes=116, commitment="medium", popularity=.82, quality_prior=.94, tags=["language", "aliens", "time", "philosophy"], features={"philosophical_depth":.91,"narrative_complexity":.86,"world_building":.68,"emotional_intensity":.82,"scientific_grounding":.7,"pacing":.38,"darkness":.45,"originality":.92,"information_density":.65}, downsides=["Deliberately slow pacing", "Emotionally heavy"]),
    dict(media_type="movie", title="Primer", language="English", runtime_minutes=77, commitment="short", popularity=.35, quality_prior=.82, hidden_gem=True, tags=["time travel", "engineering", "logic"], features={"philosophical_depth":.72,"narrative_complexity":.99,"world_building":.48,"emotional_intensity":.35,"scientific_grounding":.88,"pacing":.62,"darkness":.43,"originality":.96,"information_density":.92}, downsides=["Extremely difficult to follow", "Minimal emotional guidance"]),
    dict(media_type="movie", title="Coherence", language="English", runtime_minutes=89, commitment="short", popularity=.38, quality_prior=.83, hidden_gem=True, tags=["parallel worlds", "logic", "psychology"], features={"philosophical_depth":.7,"narrative_complexity":.9,"world_building":.52,"emotional_intensity":.71,"scientific_grounding":.55,"pacing":.75,"darkness":.63,"originality":.91,"information_density":.71}, downsides=["Low-budget production style", "Intentionally disorienting"]),
    dict(media_type="telugu_movie", title="Eega", language="Telugu", runtime_minutes=145, commitment="long", popularity=.8, quality_prior=.87, tags=["fantasy", "revenge", "originality"], features={"philosophical_depth":.35,"narrative_complexity":.55,"world_building":.72,"emotional_intensity":.73,"scientific_grounding":.1,"pacing":.78,"darkness":.36,"originality":.95,"information_density":.3}, downsides=["Broad comedy may not suit every mood", "Fantasy logic over realism"]),
    dict(media_type="telugu_movie", title="Agent Sai Srinivasa Athreya", language="Telugu", runtime_minutes=148, commitment="long", popularity=.66, quality_prior=.86, hidden_gem=True, tags=["detective", "logic", "mystery"], features={"philosophical_depth":.46,"narrative_complexity":.77,"world_building":.42,"emotional_intensity":.63,"scientific_grounding":.45,"pacing":.75,"darkness":.51,"originality":.82,"information_density":.62}, downsides=["Comedy and mystery tones alternate", "Longer than a typical mystery"]),
    dict(media_type="series", title="Dark", language="German", status="completed", commitment="very_long", popularity=.87, quality_prior=.95, tags=["time travel", "causality", "family", "philosophy"], features={"philosophical_depth":.94,"narrative_complexity":.99,"world_building":.91,"emotional_intensity":.83,"scientific_grounding":.64,"pacing":.48,"darkness":.91,"originality":.94,"information_density":.9}, downsides=["Requires close attention", "Very dark tone", "Large character graph"]),
    dict(media_type="series", title="Severance", language="English", status="ongoing", commitment="long", popularity=.88, quality_prior=.95, tags=["work", "identity", "psychology", "mystery"], features={"philosophical_depth":.9,"narrative_complexity":.86,"world_building":.84,"emotional_intensity":.72,"scientific_grounding":.42,"pacing":.4,"darkness":.68,"originality":.96,"information_density":.68}, downsides=["Slow-burn setup", "Ongoing story"]),
    dict(media_type="anime", title="Steins;Gate", language="Japanese", status="completed", commitment="very_long", popularity=.9, quality_prior=.96, dub_available=True, tags=["time travel", "science", "causality", "psychology"], features={"philosophical_depth":.87,"narrative_complexity":.94,"world_building":.76,"emotional_intensity":.92,"scientific_grounding":.55,"pacing":.37,"darkness":.74,"originality":.94,"information_density":.75}, downsides=["Slow first half", "Early comedy may interrupt serious tone"]),
    dict(media_type="anime", title="Psycho-Pass", language="Japanese", status="completed", commitment="very_long", popularity=.78, quality_prior=.91, dub_available=True, tags=["AI", "ethics", "surveillance", "psychology"], features={"philosophical_depth":.92,"narrative_complexity":.82,"world_building":.91,"emotional_intensity":.78,"scientific_grounding":.48,"pacing":.72,"darkness":.88,"originality":.9,"information_density":.72}, downsides=["Graphic violence", "Later seasons are less consistent"]),
    dict(media_type="anime", title="Planetes", language="Japanese", status="completed", commitment="very_long", popularity=.42, quality_prior=.9, hidden_gem=True, dub_available=True, tags=["space", "engineering", "work", "humanity"], features={"philosophical_depth":.83,"narrative_complexity":.7,"world_building":.88,"emotional_intensity":.76,"scientific_grounding":.92,"pacing":.46,"darkness":.42,"originality":.86,"information_density":.68}, downsides=["Episodic opening", "Older visual style"]),
    dict(media_type="manga", title="The Climber", language="Japanese", status="completed", commitment="very_long", popularity=.45, quality_prior=.93, hidden_gem=True, tags=["psychology", "solitude", "mountaineering"], features={"philosophical_depth":.88,"narrative_complexity":.72,"world_building":.55,"emotional_intensity":.94,"scientific_grounding":.65,"pacing":.52,"darkness":.82,"originality":.91,"information_density":.58}, downsides=["Psychologically intense", "Long reading commitment"]),
    dict(media_type="manhwa", title="The Horizon", language="Korean", status="completed", commitment="short", popularity=.46, quality_prior=.91, hidden_gem=True, tags=["war", "humanity", "existentialism"], features={"philosophical_depth":.93,"narrative_complexity":.63,"world_building":.5,"emotional_intensity":.98,"scientific_grounding":.2,"pacing":.72,"darkness":.96,"originality":.88,"information_density":.52}, downsides=["Extremely bleak", "Emotionally demanding"]),
    dict(media_type="youtube_channel", title="3Blue1Brown", language="English", commitment="variable", popularity=.87, quality_prior=.98, tags=["mathematics", "visual explanation", "intuition"], features={"philosophical_depth":.55,"narrative_complexity":.55,"world_building":.1,"emotional_intensity":.25,"scientific_grounding":.98,"pacing":.7,"darkness":.05,"originality":.97,"information_density":.9,"technical_depth":.82,"visual_explanation":.99}, downsides=["Some topics still require mathematical prerequisites"]),
    dict(media_type="youtube_channel", title="Veritasium", language="English", commitment="variable", popularity=.95, quality_prior=.92, tags=["science", "physics", "experiments"], features={"philosophical_depth":.54,"narrative_complexity":.6,"world_building":.1,"emotional_intensity":.35,"scientific_grounding":.93,"pacing":.78,"darkness":.08,"originality":.87,"information_density":.78,"technical_depth":.66,"visual_explanation":.87}, downsides=["Some videos prioritize broad accessibility over technical depth"]),
    dict(media_type="youtube_channel", title="Asianometry", language="English", commitment="variable", popularity=.36, quality_prior=.9, hidden_gem=True, tags=["semiconductors", "technology", "history", "engineering"], features={"philosophical_depth":.45,"narrative_complexity":.66,"world_building":.1,"emotional_intensity":.16,"scientific_grounding":.91,"pacing":.58,"darkness":.08,"originality":.82,"information_density":.94,"technical_depth":.79,"visual_explanation":.66}, downsides=["Dry presentation style", "Dense industry context"]),
    dict(media_type="youtube_channel", title="PBS Space Time", language="English", commitment="variable", popularity=.68, quality_prior=.96, tags=["physics", "space", "cosmology", "mathematics"], features={"philosophical_depth":.82,"narrative_complexity":.83,"world_building":.1,"emotional_intensity":.2,"scientific_grounding":.99,"pacing":.51,"darkness":.08,"originality":.9,"information_density":.97,"technical_depth":.93,"visual_explanation":.83}, downsides=["High conceptual difficulty", "Often assumes prior physics knowledge"]),
]


def seed_catalog(db: Session) -> None:
    if db.scalar(select(MediaItem.id).limit(1)) is not None:
        return
    db.add_all([MediaItem(**item, description="Curated starter-catalog item.") for item in CATALOG])
    db.commit()
